from docente import DocenteController
from alumno import AlumnoController
from curso import CursoController
from enunciado import EnunciadoController
from caso_de_prueba import CasoDePruebaController
from ejercicio import EjercicioController
from docente_inscripto import DocenteInscriptoController
from grupo import GrupoController
