from docente import DocenteController
from alumno import AlumnoController
from curso import CursoController
from enunciado import EnunciadoController
from correccion import CorreccionController
from misentregas import MisEntregasController
from tarea_fuente import TareaFuenteController
from tarea_prueba import TareaPruebaController
from examenes import ExamenFinalController
from entregas import EntregasController

